### ISSUE TITLE
無駄な列

### ISSUE THREAD

**Issue by yuma-kishimoto** [c0a21155/ProjExD#3]
https://github.com/c0a21155/ProjExD/blob/4504c406221d84fb681a6cc3f3ec5f33bc82d3bc/ex02/calc.py#L3

1、２行は良いけどそれ以上だと見にくく感じました。
あとプラスと実行以外のボタンを追加した方が良いですね。
必要な部分にメモを書くことを自分もマネします。

**Comment by c0a21155** [comment]
空白の行を1行まで減らしました。
delボタンを追加し、左クリックで表示文字列の右側一文字、右クリックで表示文字列を全て削除するように変更しました。
