### ISSUE TITLE
「＝」の右クリックデリートが直感的にわかりずらいかもしれない。

### ISSUE THREAD

**Issue by c0a21165** [c0a21155/ProjExD#5]
https://github.com/c0a21155/ProjExD/blob/4504c406221d84fb681a6cc3f3ec5f33bc82d3bc/ex02/calc.py#L69

**Comment by c0a21155** [comment]
issues1人目から同様の要望をいただきました。delボタンを追加し、delボタンを左クリックで1文字削除。右クリックで全削除できるようにしました。
