### ISSUE TITLE
まとめれそう？

### ISSUE THREAD

**Issue by c0a21162** [c0a21155/ProjExD#6]
https://github.com/c0a21155/ProjExD/blob/eb7f9dc998894e5f5084407610afced0ad77b060/ex03/maze.py#L40

if cx == 1350 and cy == 750:
にまとめられそう！

**Comment by c0a21155** [comment]
if cx == 1350:
        if cy == 150:
            canvas.coords("kokaton2", cx, cy)
        elif cy == 750:
            root.destroy()
と変更しました。
変更後、無事実行成功しました。
情報ありがとうございます。
