### ISSUE TITLE
elifの活用

### ISSUE THREAD

**Issue by yuma-kishimoto** [c0a21155/ProjExD#7]
https://github.com/c0a21155/ProjExD/blob/eb7f9dc998894e5f5084407610afced0ad77b060/ex03/maze.py#L41

37行目と40行目が同じ文になっていることもあり、41行目はelifに出来ると思います。
eilfにすることで文章がスッキリするのではないでしょうか。

**Comment by c0a21155** [comment]
もう一人のissueで同様の指摘をされたので、
    if cx == 1350:
        if cy == 150:
            canvas.coords("kokaton2", cx, cy)
        elif cy == 750:
            root.destroy()
と変更しました。
変更後もプログラムを無事実行できました。
情報ありがとうございます。
