### ISSUE TITLE
コメントを追加するか削除するか

### ISSUE THREAD

**Issue by c0a21162** [c0a21155/ProjExD#8]
https://github.com/c0a21155/ProjExD/blob/29d59f2f2454240faa72865210209dd9471d5c1b/ex04/dodge_bomb.py#L82

実装したかった機能として残してるならどんな機能なのかをコメントして残した方がいいと思う！
それかもしいらないなら消しちゃった方がいいと思う！

**Comment by c0a21155** [comment]
82行目では、キー"w","g"で動かした爆弾を枠外へ出ないようにしようとしたプログラムです。しかし、上手くいきませんでした。
機能として、コメントに残しておきました。
アドバイスありがとうございます。
