### ISSUE TITLE
コメント文を複数行する

### ISSUE THREAD

**Issue by yuma-kishimoto** [c0a21155/ProjExD#9]
https://github.com/c0a21155/ProjExD/blob/a07b08db8315b99e6b75f00c6b115c3b26182258/ex04/dodge_bomb.py#L82

#で1つ1つやってもいいのですが、
はじめとおわりにシングルクォーテーションかダブルクォーテーションを3つすることでコメント文に出来ます。
早くなると思うので参考にしてみてください。

**Comment by c0a21155** [comment]
アドバイスを頂いてから実際にやってみました。
しかし、"""or'''で挟んだ行が文字扱い("〇"のようになる)になってしまいます。
なので、変更はなしにしようと思います。
アドバイスありがとうございます。
